name: blue_harbor_dev_db

services:
  db:
    image: postgres:16
    container_name: blue_harbor_dev_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blue_harbor_dev_db
